<?php
/**
 * Class DT_Mapping_Module_Migration_0004
 *
 * @note  Renaming of countries from formal titles to friendly titles.
 */

class DT_Mapping_Module_Migration_0004 extends DT_Mapping_Module_Migration {
    public function up() {
        global $wpdb;

        // sql for updating country names in dt_geonames
        $sql = [];
        $sql[] = "UPDATE dt_geonames SET name = 'Andorra' WHERE geonameid = 3041565";
        $sql[] = "UPDATE dt_geonames SET name = 'United Arab Emirates' WHERE geonameid = 290557";
        $sql[] = "UPDATE dt_geonames SET name = 'Afghanistan' WHERE geonameid = 1149361";
        $sql[] = "UPDATE dt_geonames SET name = 'Antigua And Barbuda' WHERE geonameid = 3576396";
        $sql[] = "UPDATE dt_geonames SET name = 'Anguilla' WHERE geonameid = 3573511";
        $sql[] = "UPDATE dt_geonames SET name = 'Albania' WHERE geonameid = 783754";
        $sql[] = "UPDATE dt_geonames SET name = 'Armenia' WHERE geonameid = 174982";
        $sql[] = "UPDATE dt_geonames SET name = 'Angola' WHERE geonameid = 3351879";
        $sql[] = "UPDATE dt_geonames SET name = 'Argentina' WHERE geonameid = 3865483";
        $sql[] = "UPDATE dt_geonames SET name = 'American Samoa' WHERE geonameid = 5880801";
        $sql[] = "UPDATE dt_geonames SET name = 'Austria' WHERE geonameid = 2782113";
        $sql[] = "UPDATE dt_geonames SET name = 'Australia' WHERE geonameid = 2077456";
        $sql[] = "UPDATE dt_geonames SET name = 'Aruba' WHERE geonameid = 3577279";
        $sql[] = "UPDATE dt_geonames SET name = 'Azerbaijan' WHERE geonameid = 587116";
        $sql[] = "UPDATE dt_geonames SET name = 'Bosnia And Herzegovina' WHERE geonameid = 3277605";
        $sql[] = "UPDATE dt_geonames SET name = 'Barbados' WHERE geonameid = 3374084";
        $sql[] = "UPDATE dt_geonames SET name = 'Bangladesh' WHERE geonameid = 1210997";
        $sql[] = "UPDATE dt_geonames SET name = 'Belgium' WHERE geonameid = 2802361";
        $sql[] = "UPDATE dt_geonames SET name = 'Burkina Faso' WHERE geonameid = 2361809";
        $sql[] = "UPDATE dt_geonames SET name = 'Bulgaria' WHERE geonameid = 732800";
        $sql[] = "UPDATE dt_geonames SET name = 'Bahrain' WHERE geonameid = 290291";
        $sql[] = "UPDATE dt_geonames SET name = 'Burundi' WHERE geonameid = 433561";
        $sql[] = "UPDATE dt_geonames SET name = 'Benin' WHERE geonameid = 2395170";
        $sql[] = "UPDATE dt_geonames SET name = 'Saint Barthelemy' WHERE geonameid = 3578476";
        $sql[] = "UPDATE dt_geonames SET name = 'Bermuda' WHERE geonameid = 3573345";
        $sql[] = "UPDATE dt_geonames SET name = 'Brunei' WHERE geonameid = 1820814";
        $sql[] = "UPDATE dt_geonames SET name = 'Bolivia' WHERE geonameid = 3923057";
        $sql[] = "UPDATE dt_geonames SET name = 'Brazil' WHERE geonameid = 3469034";
        $sql[] = "UPDATE dt_geonames SET name = 'Bahamas, The' WHERE geonameid = 3572887";
        $sql[] = "UPDATE dt_geonames SET name = 'Bhutan' WHERE geonameid = 1252634";
        $sql[] = "UPDATE dt_geonames SET name = 'Botswana' WHERE geonameid = 933860";
        $sql[] = "UPDATE dt_geonames SET name = 'Belarus' WHERE geonameid = 630336";
        $sql[] = "UPDATE dt_geonames SET name = 'Belize' WHERE geonameid = 3582678";
        $sql[] = "UPDATE dt_geonames SET name = 'Canada' WHERE geonameid = 6251999";
        $sql[] = "UPDATE dt_geonames SET name = 'Congo (Kinshasa)' WHERE geonameid = 203312";
        $sql[] = "UPDATE dt_geonames SET name = 'Central African Republic' WHERE geonameid = 239880";
        $sql[] = "UPDATE dt_geonames SET name = 'Congo (Brazzaville)' WHERE geonameid = 2260494";
        $sql[] = "UPDATE dt_geonames SET name = 'Switzerland' WHERE geonameid = 2658434";
        $sql[] = "UPDATE dt_geonames SET name = 'Côte D’Ivoire' WHERE geonameid = 2287781";
        $sql[] = "UPDATE dt_geonames SET name = 'Cook Islands' WHERE geonameid = 1899402";
        $sql[] = "UPDATE dt_geonames SET name = 'Chile' WHERE geonameid = 3895114";
        $sql[] = "UPDATE dt_geonames SET name = 'Cameroon' WHERE geonameid = 2233387";
        $sql[] = "UPDATE dt_geonames SET name = 'China' WHERE geonameid = 1814991";
        $sql[] = "UPDATE dt_geonames SET name = 'Colombia' WHERE geonameid = 3686110";
        $sql[] = "UPDATE dt_geonames SET name = 'Costa Rica' WHERE geonameid = 3624060";
        $sql[] = "UPDATE dt_geonames SET name = 'Cuba' WHERE geonameid = 3562981";
        $sql[] = "UPDATE dt_geonames SET name = 'Cabo Verde' WHERE geonameid = 3374766";
        $sql[] = "UPDATE dt_geonames SET name = 'Curaçao' WHERE geonameid = 7626836";
        $sql[] = "UPDATE dt_geonames SET name = 'Christmas Island' WHERE geonameid = 2078138";
        $sql[] = "UPDATE dt_geonames SET name = 'Cyprus' WHERE geonameid = 146669";
        $sql[] = "UPDATE dt_geonames SET name = 'Czechia' WHERE geonameid = 3077311";
        $sql[] = "UPDATE dt_geonames SET name = 'Germany' WHERE geonameid = 2921044";
        $sql[] = "UPDATE dt_geonames SET name = 'Djibouti' WHERE geonameid = 223816";
        $sql[] = "UPDATE dt_geonames SET name = 'Denmark' WHERE geonameid = 2623032";
        $sql[] = "UPDATE dt_geonames SET name = 'Dominica' WHERE geonameid = 3575830";
        $sql[] = "UPDATE dt_geonames SET name = 'Dominican Republic' WHERE geonameid = 3508796";
        $sql[] = "UPDATE dt_geonames SET name = 'Algeria' WHERE geonameid = 2589581";
        $sql[] = "UPDATE dt_geonames SET name = 'Ecuador' WHERE geonameid = 3658394";
        $sql[] = "UPDATE dt_geonames SET name = 'Estonia' WHERE geonameid = 453733";
        $sql[] = "UPDATE dt_geonames SET name = 'Egypt' WHERE geonameid = 357994";
        $sql[] = "UPDATE dt_geonames SET name = 'Western Sahara' WHERE geonameid = 2461445";
        $sql[] = "UPDATE dt_geonames SET name = 'Eritrea' WHERE geonameid = 338010";
        $sql[] = "UPDATE dt_geonames SET name = 'Spain' WHERE geonameid = 2510769";
        $sql[] = "UPDATE dt_geonames SET name = 'Ethiopia' WHERE geonameid = 337996";
        $sql[] = "UPDATE dt_geonames SET name = 'Finland' WHERE geonameid = 660013";
        $sql[] = "UPDATE dt_geonames SET name = 'Fiji' WHERE geonameid = 2205218";
        $sql[] = "UPDATE dt_geonames SET name = 'Falkland Islands (Islas Malvinas)' WHERE geonameid = 3474414";
        $sql[] = "UPDATE dt_geonames SET name = 'Micronesia, Federated States Of' WHERE geonameid = 2081918";
        $sql[] = "UPDATE dt_geonames SET name = 'Faroe Islands' WHERE geonameid = 2622320";
        $sql[] = "UPDATE dt_geonames SET name = 'France' WHERE geonameid = 3017382";
        $sql[] = "UPDATE dt_geonames SET name = 'Gabon' WHERE geonameid = 2400553";
        $sql[] = "UPDATE dt_geonames SET name = 'United Kingdom' WHERE geonameid = 2635167";
        $sql[] = "UPDATE dt_geonames SET name = 'Grenada' WHERE geonameid = 3580239";
        $sql[] = "UPDATE dt_geonames SET name = 'Georgia' WHERE geonameid = 614540";
        $sql[] = "UPDATE dt_geonames SET name = 'French Guiana' WHERE geonameid = 3381670";
        $sql[] = "UPDATE dt_geonames SET name = 'Guernsey' WHERE geonameid = 3042362";
        $sql[] = "UPDATE dt_geonames SET name = 'Ghana' WHERE geonameid = 2300660";
        $sql[] = "UPDATE dt_geonames SET name = 'Gibraltar' WHERE geonameid = 2411586";
        $sql[] = "UPDATE dt_geonames SET name = 'Greenland' WHERE geonameid = 3425505";
        $sql[] = "UPDATE dt_geonames SET name = 'Gambia, The' WHERE geonameid = 2413451";
        $sql[] = "UPDATE dt_geonames SET name = 'Guinea' WHERE geonameid = 2420477";
        $sql[] = "UPDATE dt_geonames SET name = 'Guadeloupe' WHERE geonameid = 3579143";
        $sql[] = "UPDATE dt_geonames SET name = 'Equatorial Guinea' WHERE geonameid = 2309096";
        $sql[] = "UPDATE dt_geonames SET name = 'Greece' WHERE geonameid = 390903";
        $sql[] = "UPDATE dt_geonames SET name = 'South Georgia And South Sandwich Islands' WHERE geonameid = 3474415";
        $sql[] = "UPDATE dt_geonames SET name = 'Guatemala' WHERE geonameid = 3595528";
        $sql[] = "UPDATE dt_geonames SET name = 'Guam' WHERE geonameid = 4043988";
        $sql[] = "UPDATE dt_geonames SET name = 'Guinea-Bissau' WHERE geonameid = 2372248";
        $sql[] = "UPDATE dt_geonames SET name = 'Guyana' WHERE geonameid = 3378535";
        $sql[] = "UPDATE dt_geonames SET name = 'Hong Kong' WHERE geonameid = 1819730";
        $sql[] = "UPDATE dt_geonames SET name = 'Honduras' WHERE geonameid = 3608932";
        $sql[] = "UPDATE dt_geonames SET name = 'Croatia' WHERE geonameid = 3202326";
        $sql[] = "UPDATE dt_geonames SET name = 'Haiti' WHERE geonameid = 3723988";
        $sql[] = "UPDATE dt_geonames SET name = 'Hungary' WHERE geonameid = 719819";
        $sql[] = "UPDATE dt_geonames SET name = 'Indonesia' WHERE geonameid = 1643084";
        $sql[] = "UPDATE dt_geonames SET name = 'Ireland' WHERE geonameid = 2963597";
        $sql[] = "UPDATE dt_geonames SET name = 'Israel' WHERE geonameid = 294640";
        $sql[] = "UPDATE dt_geonames SET name = 'Isle Of Man' WHERE geonameid = 3042225";
        $sql[] = "UPDATE dt_geonames SET name = 'India' WHERE geonameid = 1269750";
        $sql[] = "UPDATE dt_geonames SET name = 'British Indian Ocean Territory' WHERE geonameid = 1282588";
        $sql[] = "UPDATE dt_geonames SET name = 'Iraq' WHERE geonameid = 99237";
        $sql[] = "UPDATE dt_geonames SET name = 'Iran' WHERE geonameid = 130758";
        $sql[] = "UPDATE dt_geonames SET name = 'Iceland' WHERE geonameid = 2629691";
        $sql[] = "UPDATE dt_geonames SET name = 'Italy' WHERE geonameid = 3175395";
        $sql[] = "UPDATE dt_geonames SET name = 'Jersey' WHERE geonameid = 3042142";
        $sql[] = "UPDATE dt_geonames SET name = 'Jamaica' WHERE geonameid = 3489940";
        $sql[] = "UPDATE dt_geonames SET name = 'Jordan' WHERE geonameid = 248816";
        $sql[] = "UPDATE dt_geonames SET name = 'Japan' WHERE geonameid = 1861060";
        $sql[] = "UPDATE dt_geonames SET name = 'Kenya' WHERE geonameid = 192950";
        $sql[] = "UPDATE dt_geonames SET name = 'Kyrgyzstan' WHERE geonameid = 1527747";
        $sql[] = "UPDATE dt_geonames SET name = 'Cambodia' WHERE geonameid = 1831722";
        $sql[] = "UPDATE dt_geonames SET name = 'Kiribati' WHERE geonameid = 4030945";
        $sql[] = "UPDATE dt_geonames SET name = 'Comoros' WHERE geonameid = 921929";
        $sql[] = "UPDATE dt_geonames SET name = 'Saint Kitts And Nevis' WHERE geonameid = 3575174";
        $sql[] = "UPDATE dt_geonames SET name = 'Korea, North' WHERE geonameid = 1873107";
        $sql[] = "UPDATE dt_geonames SET name = 'Korea, South' WHERE geonameid = 1835841";
        $sql[] = "UPDATE dt_geonames SET name = 'Kuwait' WHERE geonameid = 285570";
        $sql[] = "UPDATE dt_geonames SET name = 'Cayman Islands' WHERE geonameid = 3580718";
        $sql[] = "UPDATE dt_geonames SET name = 'Kazakhstan' WHERE geonameid = 1522867";
        $sql[] = "UPDATE dt_geonames SET name = 'Laos' WHERE geonameid = 1655842";
        $sql[] = "UPDATE dt_geonames SET name = 'Lebanon' WHERE geonameid = 272103";
        $sql[] = "UPDATE dt_geonames SET name = 'Saint Lucia' WHERE geonameid = 3576468";
        $sql[] = "UPDATE dt_geonames SET name = 'Liechtenstein' WHERE geonameid = 3042058";
        $sql[] = "UPDATE dt_geonames SET name = 'Sri Lanka' WHERE geonameid = 1227603";
        $sql[] = "UPDATE dt_geonames SET name = 'Liberia' WHERE geonameid = 2275384";
        $sql[] = "UPDATE dt_geonames SET name = 'Lesotho' WHERE geonameid = 932692";
        $sql[] = "UPDATE dt_geonames SET name = 'Lithuania' WHERE geonameid = 597427";
        $sql[] = "UPDATE dt_geonames SET name = 'Luxembourg' WHERE geonameid = 2960313";
        $sql[] = "UPDATE dt_geonames SET name = 'Latvia' WHERE geonameid = 458258";
        $sql[] = "UPDATE dt_geonames SET name = 'Libya' WHERE geonameid = 2215636";
        $sql[] = "UPDATE dt_geonames SET name = 'Morocco' WHERE geonameid = 2542007";
        $sql[] = "UPDATE dt_geonames SET name = 'Monaco' WHERE geonameid = 2993457";
        $sql[] = "UPDATE dt_geonames SET name = 'Moldova' WHERE geonameid = 617790";
        $sql[] = "UPDATE dt_geonames SET name = 'Montenegro' WHERE geonameid = 3194884";
        $sql[] = "UPDATE dt_geonames SET name = 'Saint Martin' WHERE geonameid = 3578421";
        $sql[] = "UPDATE dt_geonames SET name = 'Madagascar' WHERE geonameid = 1062947";
        $sql[] = "UPDATE dt_geonames SET name = 'Marshall Islands' WHERE geonameid = 2080185";
        $sql[] = "UPDATE dt_geonames SET name = 'Macedonia' WHERE geonameid = 718075";
        $sql[] = "UPDATE dt_geonames SET name = 'Mali' WHERE geonameid = 2453866";
        $sql[] = "UPDATE dt_geonames SET name = 'Burma' WHERE geonameid = 1327865";
        $sql[] = "UPDATE dt_geonames SET name = 'Mongolia' WHERE geonameid = 2029969";
        $sql[] = "UPDATE dt_geonames SET name = 'Macau' WHERE geonameid = 1821275";
        $sql[] = "UPDATE dt_geonames SET name = 'Northern Mariana Islands' WHERE geonameid = 4041468";
        $sql[] = "UPDATE dt_geonames SET name = 'Martinique' WHERE geonameid = 3570311";
        $sql[] = "UPDATE dt_geonames SET name = 'Mauritania' WHERE geonameid = 2378080";
        $sql[] = "UPDATE dt_geonames SET name = 'Montserrat' WHERE geonameid = 3578097";
        $sql[] = "UPDATE dt_geonames SET name = 'Malta' WHERE geonameid = 2562770";
        $sql[] = "UPDATE dt_geonames SET name = 'Mauritius' WHERE geonameid = 934292";
        $sql[] = "UPDATE dt_geonames SET name = 'Maldives' WHERE geonameid = 1282028";
        $sql[] = "UPDATE dt_geonames SET name = 'Malawi' WHERE geonameid = 927384";
        $sql[] = "UPDATE dt_geonames SET name = 'Mexico' WHERE geonameid = 3996063";
        $sql[] = "UPDATE dt_geonames SET name = 'Malaysia' WHERE geonameid = 1733045";
        $sql[] = "UPDATE dt_geonames SET name = 'Mozambique' WHERE geonameid = 1036973";
        $sql[] = "UPDATE dt_geonames SET name = 'Namibia' WHERE geonameid = 3355338";
        $sql[] = "UPDATE dt_geonames SET name = 'New Caledonia' WHERE geonameid = 2139685";
        $sql[] = "UPDATE dt_geonames SET name = 'Niger' WHERE geonameid = 2440476";
        $sql[] = "UPDATE dt_geonames SET name = 'Norfolk Island' WHERE geonameid = 2155115";
        $sql[] = "UPDATE dt_geonames SET name = 'Nigeria' WHERE geonameid = 2328926";
        $sql[] = "UPDATE dt_geonames SET name = 'Nicaragua' WHERE geonameid = 3617476";
        $sql[] = "UPDATE dt_geonames SET name = 'Netherlands' WHERE geonameid = 2750405";
        $sql[] = "UPDATE dt_geonames SET name = 'Norway' WHERE geonameid = 3144096";
        $sql[] = "UPDATE dt_geonames SET name = 'Nepal' WHERE geonameid = 1282988";
        $sql[] = "UPDATE dt_geonames SET name = 'Nauru' WHERE geonameid = 2110425";
        $sql[] = "UPDATE dt_geonames SET name = 'Niue' WHERE geonameid = 4036232";
        $sql[] = "UPDATE dt_geonames SET name = 'New Zealand' WHERE geonameid = 2186224";
        $sql[] = "UPDATE dt_geonames SET name = 'Oman' WHERE geonameid = 286963";
        $sql[] = "UPDATE dt_geonames SET name = 'Panama' WHERE geonameid = 3703430";
        $sql[] = "UPDATE dt_geonames SET name = 'Peru' WHERE geonameid = 3932488";
        $sql[] = "UPDATE dt_geonames SET name = 'French Polynesia' WHERE geonameid = 4030656";
        $sql[] = "UPDATE dt_geonames SET name = 'Papua New Guinea' WHERE geonameid = 2088628";
        $sql[] = "UPDATE dt_geonames SET name = 'Philippines' WHERE geonameid = 1694008";
        $sql[] = "UPDATE dt_geonames SET name = 'Pakistan' WHERE geonameid = 1168579";
        $sql[] = "UPDATE dt_geonames SET name = 'Poland' WHERE geonameid = 798544";
        $sql[] = "UPDATE dt_geonames SET name = 'Saint Pierre And Miquelon' WHERE geonameid = 3424932";
        $sql[] = "UPDATE dt_geonames SET name = 'Puerto Rico' WHERE geonameid = 4566966";
        $sql[] = "UPDATE dt_geonames SET name = 'Portugal' WHERE geonameid = 2264397";
        $sql[] = "UPDATE dt_geonames SET name = 'Palau' WHERE geonameid = 1559582";
        $sql[] = "UPDATE dt_geonames SET name = 'Paraguay' WHERE geonameid = 3437598";
        $sql[] = "UPDATE dt_geonames SET name = 'Qatar' WHERE geonameid = 289688";
        $sql[] = "UPDATE dt_geonames SET name = 'Reunion' WHERE geonameid = 935317";
        $sql[] = "UPDATE dt_geonames SET name = 'Romania' WHERE geonameid = 798549";
        $sql[] = "UPDATE dt_geonames SET name = 'Serbia' WHERE geonameid = 6290252";
        $sql[] = "UPDATE dt_geonames SET name = 'Russia' WHERE geonameid = 2017370";
        $sql[] = "UPDATE dt_geonames SET name = 'Rwanda' WHERE geonameid = 49518";
        $sql[] = "UPDATE dt_geonames SET name = 'Saudi Arabia' WHERE geonameid = 102358";
        $sql[] = "UPDATE dt_geonames SET name = 'Solomon Islands' WHERE geonameid = 2103350";
        $sql[] = "UPDATE dt_geonames SET name = 'Seychelles' WHERE geonameid = 241170";
        $sql[] = "UPDATE dt_geonames SET name = 'Sudan' WHERE geonameid = 366755";
        $sql[] = "UPDATE dt_geonames SET name = 'Sweden' WHERE geonameid = 2661886";
        $sql[] = "UPDATE dt_geonames SET name = 'Singapore' WHERE geonameid = 1880251";
        $sql[] = "UPDATE dt_geonames SET name = 'Saint Helena, Ascension, And Tristan Da Cunha' WHERE geonameid = 3370751";
        $sql[] = "UPDATE dt_geonames SET name = 'Slovenia' WHERE geonameid = 3190538";
        $sql[] = "UPDATE dt_geonames SET name = 'Slovakia' WHERE geonameid = 3057568";
        $sql[] = "UPDATE dt_geonames SET name = 'Sierra Leone' WHERE geonameid = 2403846";
        $sql[] = "UPDATE dt_geonames SET name = 'San Marino' WHERE geonameid = 3168068";
        $sql[] = "UPDATE dt_geonames SET name = 'Senegal' WHERE geonameid = 2245662";
        $sql[] = "UPDATE dt_geonames SET name = 'Somalia' WHERE geonameid = 51537";
        $sql[] = "UPDATE dt_geonames SET name = 'Suriname' WHERE geonameid = 3382998";
        $sql[] = "UPDATE dt_geonames SET name = 'South Sudan' WHERE geonameid = 7909807";
        $sql[] = "UPDATE dt_geonames SET name = 'Sao Tome And Principe' WHERE geonameid = 2410758";
        $sql[] = "UPDATE dt_geonames SET name = 'El Salvador' WHERE geonameid = 3585968";
        $sql[] = "UPDATE dt_geonames SET name = 'Sint Maarten' WHERE geonameid = 7609695";
        $sql[] = "UPDATE dt_geonames SET name = 'Syria' WHERE geonameid = 163843";
        $sql[] = "UPDATE dt_geonames SET name = 'Swaziland' WHERE geonameid = 934841";
        $sql[] = "UPDATE dt_geonames SET name = 'Turks And Caicos Islands' WHERE geonameid = 3576916";
        $sql[] = "UPDATE dt_geonames SET name = 'Chad' WHERE geonameid = 2434508";
        $sql[] = "UPDATE dt_geonames SET name = 'Togo' WHERE geonameid = 2363686";
        $sql[] = "UPDATE dt_geonames SET name = 'Thailand' WHERE geonameid = 1605651";
        $sql[] = "UPDATE dt_geonames SET name = 'Tajikistan' WHERE geonameid = 1220409";
        $sql[] = "UPDATE dt_geonames SET name = 'Timor-Leste' WHERE geonameid = 1966436";
        $sql[] = "UPDATE dt_geonames SET name = 'Turkmenistan' WHERE geonameid = 1218197";
        $sql[] = "UPDATE dt_geonames SET name = 'Tunisia' WHERE geonameid = 2464461";
        $sql[] = "UPDATE dt_geonames SET name = 'Tonga' WHERE geonameid = 4032283";
        $sql[] = "UPDATE dt_geonames SET name = 'Turkey' WHERE geonameid = 298795";
        $sql[] = "UPDATE dt_geonames SET name = 'Trinidad And Tobago' WHERE geonameid = 3573591";
        $sql[] = "UPDATE dt_geonames SET name = 'Tuvalu' WHERE geonameid = 2110297";
        $sql[] = "UPDATE dt_geonames SET name = 'Taiwan' WHERE geonameid = 1668284";
        $sql[] = "UPDATE dt_geonames SET name = 'Tanzania' WHERE geonameid = 149590";
        $sql[] = "UPDATE dt_geonames SET name = 'Ukraine' WHERE geonameid = 690791";
        $sql[] = "UPDATE dt_geonames SET name = 'Uganda' WHERE geonameid = 226074";
        $sql[] = "UPDATE dt_geonames SET name = 'United States of America' WHERE geonameid = 6252001";
        $sql[] = "UPDATE dt_geonames SET name = 'Uruguay' WHERE geonameid = 3439705";
        $sql[] = "UPDATE dt_geonames SET name = 'Uzbekistan' WHERE geonameid = 1512440";
        $sql[] = "UPDATE dt_geonames SET name = 'Saint Vincent And The Grenadines' WHERE geonameid = 3577815";
        $sql[] = "UPDATE dt_geonames SET name = 'Venezuela' WHERE geonameid = 3625428";
        $sql[] = "UPDATE dt_geonames SET name = 'U.S. Virgin Islands' WHERE geonameid = 4796775";
        $sql[] = "UPDATE dt_geonames SET name = 'Vietnam' WHERE geonameid = 1562822";
        $sql[] = "UPDATE dt_geonames SET name = 'Vanuatu' WHERE geonameid = 2134431";
        $sql[] = "UPDATE dt_geonames SET name = 'Wallis And Futuna' WHERE geonameid = 4034749";
        $sql[] = "UPDATE dt_geonames SET name = 'Samoa' WHERE geonameid = 4034894";
        $sql[] = "UPDATE dt_geonames SET name = 'Kosovo' WHERE geonameid = 831053";
        $sql[] = "UPDATE dt_geonames SET name = 'Yemen' WHERE geonameid = 69543";
        $sql[] = "UPDATE dt_geonames SET name = 'Mayotte' WHERE geonameid = 1024031";
        $sql[] = "UPDATE dt_geonames SET name = 'South Africa' WHERE geonameid = 953987";
        $sql[] = "UPDATE dt_geonames SET name = 'Zambia' WHERE geonameid = 895949";
        $sql[] = "UPDATE dt_geonames SET name = 'Zimbabwe' WHERE geonameid = 878675";

        $results = [];
        $e = 0;
        $s = 0;
        foreach( $sql as $query ) {
            $result = $wpdb->query( $query );
            if ( $result === false ) {
                $results['error'] = $e++;
                $results['error_statements'][] = $query;
            } else {
                $results['success'] = $s++;
            }
        }

        dt_write_log( $results );


        // sql for updating country names in dt_geonames_hierarchy
        $sql = [];
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Andorra' WHERE id = 3041565";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'United Arab Emirates' WHERE id = 290557";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Afghanistan' WHERE id = 1149361";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Antigua And Barbuda' WHERE id = 3576396";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Anguilla' WHERE id = 3573511";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Albania' WHERE id = 783754";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Armenia' WHERE id = 174982";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Angola' WHERE id = 3351879";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Argentina' WHERE id = 3865483";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'American Samoa' WHERE id = 5880801";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Austria' WHERE id = 2782113";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Australia' WHERE id = 2077456";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Aruba' WHERE id = 3577279";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Azerbaijan' WHERE id = 587116";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Bosnia And Herzegovina' WHERE id = 3277605";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Barbados' WHERE id = 3374084";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Bangladesh' WHERE id = 1210997";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Belgium' WHERE id = 2802361";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Burkina Faso' WHERE id = 2361809";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Bulgaria' WHERE id = 732800";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Bahrain' WHERE id = 290291";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Burundi' WHERE id = 433561";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Benin' WHERE id = 2395170";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Saint Barthelemy' WHERE id = 3578476";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Bermuda' WHERE id = 3573345";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Brunei' WHERE id = 1820814";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Bolivia' WHERE id = 3923057";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Brazil' WHERE id = 3469034";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Bahamas, The' WHERE id = 3572887";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Bhutan' WHERE id = 1252634";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Botswana' WHERE id = 933860";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Belarus' WHERE id = 630336";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Belize' WHERE id = 3582678";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Canada' WHERE id = 6251999";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Congo (Kinshasa)' WHERE id = 203312";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Central African Republic' WHERE id = 239880";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Congo (Brazzaville)' WHERE id = 2260494";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Switzerland' WHERE id = 2658434";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Côte D’Ivoire' WHERE id = 2287781";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Cook Islands' WHERE id = 1899402";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Chile' WHERE id = 3895114";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Cameroon' WHERE id = 2233387";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'China' WHERE id = 1814991";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Colombia' WHERE id = 3686110";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Costa Rica' WHERE id = 3624060";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Cuba' WHERE id = 3562981";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Cabo Verde' WHERE id = 3374766";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Curaçao' WHERE id = 7626836";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Christmas Island' WHERE id = 2078138";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Cyprus' WHERE id = 146669";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Czechia' WHERE id = 3077311";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Germany' WHERE id = 2921044";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Djibouti' WHERE id = 223816";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Denmark' WHERE id = 2623032";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Dominica' WHERE id = 3575830";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Dominican Republic' WHERE id = 3508796";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Algeria' WHERE id = 2589581";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Ecuador' WHERE id = 3658394";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Estonia' WHERE id = 453733";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Egypt' WHERE id = 357994";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Western Sahara' WHERE id = 2461445";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Eritrea' WHERE id = 338010";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Spain' WHERE id = 2510769";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Ethiopia' WHERE id = 337996";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Finland' WHERE id = 660013";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Fiji' WHERE id = 2205218";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Falkland Islands (Islas Malvinas)' WHERE id = 3474414";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Micronesia, Federated States Of' WHERE id = 2081918";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Faroe Islands' WHERE id = 2622320";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'France' WHERE id = 3017382";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Gabon' WHERE id = 2400553";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'United Kingdom' WHERE id = 2635167";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Grenada' WHERE id = 3580239";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Georgia' WHERE id = 614540";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'French Guiana' WHERE id = 3381670";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Guernsey' WHERE id = 3042362";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Ghana' WHERE id = 2300660";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Gibraltar' WHERE id = 2411586";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Greenland' WHERE id = 3425505";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Gambia, The' WHERE id = 2413451";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Guinea' WHERE id = 2420477";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Guadeloupe' WHERE id = 3579143";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Equatorial Guinea' WHERE id = 2309096";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Greece' WHERE id = 390903";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'South Georgia And South Sandwich Islands' WHERE id = 3474415";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Guatemala' WHERE id = 3595528";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Guam' WHERE id = 4043988";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Guinea-Bissau' WHERE id = 2372248";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Guyana' WHERE id = 3378535";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Hong Kong' WHERE id = 1819730";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Honduras' WHERE id = 3608932";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Croatia' WHERE id = 3202326";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Haiti' WHERE id = 3723988";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Hungary' WHERE id = 719819";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Indonesia' WHERE id = 1643084";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Ireland' WHERE id = 2963597";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Israel' WHERE id = 294640";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Isle Of Man' WHERE id = 3042225";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'India' WHERE id = 1269750";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'British Indian Ocean Territory' WHERE id = 1282588";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Iraq' WHERE id = 99237";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Iran' WHERE id = 130758";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Iceland' WHERE id = 2629691";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Italy' WHERE id = 3175395";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Jersey' WHERE id = 3042142";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Jamaica' WHERE id = 3489940";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Jordan' WHERE id = 248816";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Japan' WHERE id = 1861060";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Kenya' WHERE id = 192950";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Kyrgyzstan' WHERE id = 1527747";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Cambodia' WHERE id = 1831722";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Kiribati' WHERE id = 4030945";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Comoros' WHERE id = 921929";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Saint Kitts And Nevis' WHERE id = 3575174";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Korea, North' WHERE id = 1873107";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Korea, South' WHERE id = 1835841";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Kuwait' WHERE id = 285570";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Cayman Islands' WHERE id = 3580718";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Kazakhstan' WHERE id = 1522867";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Laos' WHERE id = 1655842";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Lebanon' WHERE id = 272103";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Saint Lucia' WHERE id = 3576468";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Liechtenstein' WHERE id = 3042058";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Sri Lanka' WHERE id = 1227603";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Liberia' WHERE id = 2275384";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Lesotho' WHERE id = 932692";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Lithuania' WHERE id = 597427";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Luxembourg' WHERE id = 2960313";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Latvia' WHERE id = 458258";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Libya' WHERE id = 2215636";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Morocco' WHERE id = 2542007";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Monaco' WHERE id = 2993457";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Moldova' WHERE id = 617790";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Montenegro' WHERE id = 3194884";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Saint Martin' WHERE id = 3578421";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Madagascar' WHERE id = 1062947";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Marshall Islands' WHERE id = 2080185";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Macedonia' WHERE id = 718075";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Mali' WHERE id = 2453866";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Burma' WHERE id = 1327865";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Mongolia' WHERE id = 2029969";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Macau' WHERE id = 1821275";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Northern Mariana Islands' WHERE id = 4041468";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Martinique' WHERE id = 3570311";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Mauritania' WHERE id = 2378080";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Montserrat' WHERE id = 3578097";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Malta' WHERE id = 2562770";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Mauritius' WHERE id = 934292";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Maldives' WHERE id = 1282028";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Malawi' WHERE id = 927384";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Mexico' WHERE id = 3996063";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Malaysia' WHERE id = 1733045";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Mozambique' WHERE id = 1036973";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Namibia' WHERE id = 3355338";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'New Caledonia' WHERE id = 2139685";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Niger' WHERE id = 2440476";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Norfolk Island' WHERE id = 2155115";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Nigeria' WHERE id = 2328926";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Nicaragua' WHERE id = 3617476";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Netherlands' WHERE id = 2750405";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Norway' WHERE id = 3144096";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Nepal' WHERE id = 1282988";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Nauru' WHERE id = 2110425";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Niue' WHERE id = 4036232";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'New Zealand' WHERE id = 2186224";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Oman' WHERE id = 286963";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Panama' WHERE id = 3703430";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Peru' WHERE id = 3932488";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'French Polynesia' WHERE id = 4030656";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Papua New Guinea' WHERE id = 2088628";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Philippines' WHERE id = 1694008";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Pakistan' WHERE id = 1168579";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Poland' WHERE id = 798544";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Saint Pierre And Miquelon' WHERE id = 3424932";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Puerto Rico' WHERE id = 4566966";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Portugal' WHERE id = 2264397";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Palau' WHERE id = 1559582";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Paraguay' WHERE id = 3437598";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Qatar' WHERE id = 289688";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Reunion' WHERE id = 935317";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Romania' WHERE id = 798549";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Serbia' WHERE id = 6290252";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Russia' WHERE id = 2017370";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Rwanda' WHERE id = 49518";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Saudi Arabia' WHERE id = 102358";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Solomon Islands' WHERE id = 2103350";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Seychelles' WHERE id = 241170";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Sudan' WHERE id = 366755";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Sweden' WHERE id = 2661886";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Singapore' WHERE id = 1880251";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Saint Helena, Ascension, And Tristan Da Cunha' WHERE id = 3370751";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Slovenia' WHERE id = 3190538";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Slovakia' WHERE id = 3057568";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Sierra Leone' WHERE id = 2403846";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'San Marino' WHERE id = 3168068";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Senegal' WHERE id = 2245662";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Somalia' WHERE id = 51537";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Suriname' WHERE id = 3382998";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'South Sudan' WHERE id = 7909807";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Sao Tome And Principe' WHERE id = 2410758";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'El Salvador' WHERE id = 3585968";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Sint Maarten' WHERE id = 7609695";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Syria' WHERE id = 163843";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Swaziland' WHERE id = 934841";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Turks And Caicos Islands' WHERE id = 3576916";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Chad' WHERE id = 2434508";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Togo' WHERE id = 2363686";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Thailand' WHERE id = 1605651";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Tajikistan' WHERE id = 1220409";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Timor-Leste' WHERE id = 1966436";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Turkmenistan' WHERE id = 1218197";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Tunisia' WHERE id = 2464461";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Tonga' WHERE id = 4032283";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Turkey' WHERE id = 298795";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Trinidad And Tobago' WHERE id = 3573591";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Tuvalu' WHERE id = 2110297";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Taiwan' WHERE id = 1668284";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Tanzania' WHERE id = 149590";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Ukraine' WHERE id = 690791";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Uganda' WHERE id = 226074";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'United States of America' WHERE id = 6252001";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Uruguay' WHERE id = 3439705";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Uzbekistan' WHERE id = 1512440";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Saint Vincent And The Grenadines' WHERE id = 3577815";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Venezuela' WHERE id = 3625428";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'U.S. Virgin Islands' WHERE id = 4796775";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Vietnam' WHERE id = 1562822";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Vanuatu' WHERE id = 2134431";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Wallis And Futuna' WHERE id = 4034749";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Samoa' WHERE id = 4034894";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Kosovo' WHERE id = 831053";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Yemen' WHERE id = 69543";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Mayotte' WHERE id = 1024031";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'South Africa' WHERE id = 953987";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Zambia' WHERE id = 895949";
        $sql[] = "UPDATE dt_geonames_hierarchy SET name = 'Zimbabwe' WHERE id = 878675";

        $results = [];
        $e = 0;
        $s = 0;
        foreach( $sql as $query ) {
            $result = $wpdb->query( $query );
            if ( $result === false ) {
                $results['error'] = $e++;
                $results['error_statements'][] = $query;
            } else {
                $results['success'] = $s++;
            }
        }

        dt_write_log( $results );

    }

    public function down() {
        return;
    }

    public function test() {
    }

    public function get_expected_tables(): array {
        return array();
    }
}